version: '3.5'

services:
  device_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: device_service
    ports:
      - 3000:3000
    environment:
      - WEB_INTERFACE=0.0.0.0
      - WEB_PORT=3000
