version: '3.5'

services:
  jarvis:
    build:
      context: .
      dockerfile: jarvis.Dockerfile
    command: jarvis
    ports:
      - 3000:3000
    environment:
      - WEB_INTERFACE=0.0.0.0
      - WEB_PORT=3000
      - GRAPHITE_HOST=graphite
      - GRAPHITE_PORT=2003
    depends_on:
      - rabbitmq
      - postgres
      - graphite

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    volumes:
      - grafana-volume
    logging:
      driver: none

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    ports:
      - 15672:15672
      - 1883:1883
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    logging:
      driver: none

  postgres:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=jarvis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - TZ=GMT
    logging:
      driver: none

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - 2003:2003
      - 8080:8080
    restart: always
    logging:
      driver: none

volumes:
  grafana-volume:
    external: true