version: '3.5'

services:
  jarvis:
    build:
      context: .
      dockerfile: jarvis.Dockerfile
    command: jarvis
    ports:
      - 3030:3030
    environment:
      - WEB_INTERFACE=0.0.0.0
      - WEB_PORT=3000

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    ports:
      - 15672:15672
      - 1883:1883
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  postgres:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=jarvis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - TZ=GMT